version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/containershare
    environment:
      JEKYLL_ENV: production
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - checkout
      - restore_cache:
          key: containershare-{{ .Branch }}-{{ checksum "docs/Gemfile" }}
      - run:
          name: Install Ruby dependencies
          command: |
            cd docs
            bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: containershare-{{ .Branch }}-{{ checksum "docs/Gemfile" }}
          paths:
            - "vendor/bundle"
      - run:
          name: Build the Jekyll site
          command: |
            cd docs
            bundle exec jekyll build
      - run:
          name: "Install Expfactory"
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
            /bin/bash Miniconda3-latest-Linux-x86_64.sh -b 
            cd /tmp && git clone https://github.com/expfactory/expfactory.git
            cd /tmp/expfactory && $HOME/miniconda3/bin/python setup.py install
            $HOME/miniconda3/bin/python -m pip install pyaml
            cd $HOME/containershare/docs
            $HOME/miniconda3/bin/python ../tests/circle_urls.py $HOME/containershare/docs/_site
      - run:
          name: "Test Containers Library"
          command: |
            echo "Containershare!"
            cd $HOME/containershare && $HOME/miniconda3/bin/python -m unittest tests.test_library
            echo "Previewing Library Metadata"
            cat docs/_site/library.json
      - store_artifacts: 
          path: docs/_site
          destination: containershare

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
